import React from 'react';
import MetricCard from './MetricCard';

const KPIGrid = ({ metrics }) => {
    if (!metrics) return null;

    return (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <MetricCard
                label="Total Return"
                value={metrics.total_return}
                format="percent"
                tooltip="The total percentage profit or loss generated by the strategy over the backtest period."
            />
            <MetricCard
                label="CAGR"
                value={metrics.cagr}
                format="percent"
                tooltip="Compound Annual Growth Rate. The mean annual growth rate of the investment."
            />
            <MetricCard
                label="Sharpe Ratio"
                value={metrics.sharpe_ratio}
                format="decimal"
                tooltip="Measure of risk-adjusted return. Higher (>1) is better. Negative indicates return < risk-free rate."
            />
            <MetricCard
                label="Max Drawdown"
                value={metrics.max_drawdown}
                format="percent"
                tooltip="The maximum observed loss from a peak to a trough of the portfolio. Lower (closer to 0) is better."
            />
            <MetricCard
                label="Volatility"
                value={metrics.volatility}
                format="percent"
                tooltip="Annualized standard deviation of daily returns. Measures the risk or price fluctuation."
            />
            <MetricCard
                label="Win Rate"
                value={metrics.win_rate}
                format="percent"
                tooltip="Percentage of trades that resulted in a positive profit."
            />
            <MetricCard
                label="Profit Factor"
                value={metrics.profit_factor}
                format="decimal"
                tooltip="Ratio of gross profit to gross loss. >1 means profitable strategy."
            />
            <MetricCard
                label="Trades"
                value={metrics.total_trades}
                format="number"
                tooltip="Total number of completed trades during the simulation."
            />
        </div>
    );
};

export default KPIGrid;
